import { Employee, EmployeeStatus, Goal, Course } from './types';

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: '1',
    firstName: 'Paula',
    lastName: 'Nyandat',
    title: 'HR Manager',
    department: 'Human Resources',
    location: 'Nairobi, Kenya',
    email: 'paula.nyandat@enterprise.com',
    phone: '+254 700 123456',
    avatarUrl: 'https://picsum.photos/seed/paula/200/200',
    status: EmployeeStatus.ACTIVE,
    hireDate: '2015-01-10',
    performanceRating: 4.9,
  },
  {
    id: '2',
    firstName: 'Harriet',
    lastName: 'Apondi',
    title: 'Insurance Lead',
    department: 'NCBAIG Insurance',
    location: 'Nairobi, Kenya',
    email: 'harriet.apondi@enterprise.com',
    phone: '+254 700 234567',
    managerId: '1',
    avatarUrl: 'https://picsum.photos/seed/harriet/200/200',
    status: EmployeeStatus.ACTIVE,
    hireDate: '2018-06-15',
    performanceRating: 4.5,
  },
  {
    id: '3',
    firstName: 'James',
    lastName: 'Karanja',
    title: 'IT Lead',
    department: 'IT',
    location: 'Nairobi, Kenya',
    email: 'james.karanja@enterprise.com',
    phone: '+254 700 345678',
    managerId: '1',
    avatarUrl: 'https://picsum.photos/seed/james/200/200',
    status: EmployeeStatus.ACTIVE,
    hireDate: '2019-03-22',
    performanceRating: 4.8,
  },
  {
    id: '4',
    firstName: 'Confidence',
    lastName: 'Alividza',
    title: 'IT Specialist',
    department: 'IT',
    location: 'Nairobi, Kenya',
    email: 'confidence.alividza@enterprise.com',
    phone: '+254 700 456789',
    managerId: '3',
    avatarUrl: 'https://picsum.photos/seed/confidence/200/200',
    status: EmployeeStatus.ACTIVE,
    hireDate: '2020-11-01',
    performanceRating: 4.2,
  },
  {
    id: '5',
    firstName: 'Mary',
    lastName: 'Mutahi',
    title: 'IT Specialist',
    department: 'IT',
    location: 'Nairobi, Kenya',
    email: 'mary.mutahi@enterprise.com',
    phone: '+254 700 567890',
    managerId: '3',
    avatarUrl: 'https://picsum.photos/seed/mary/200/200',
    status: EmployeeStatus.ACTIVE,
    hireDate: '2017-01-10',
    performanceRating: 4.9,
  },
  {
    id: '6',
    firstName: 'Joses',
    lastName: '',
    title: 'IT Specialist',
    department: 'IT',
    location: 'Nairobi, Kenya',
    email: 'joses@enterprise.com',
    phone: '+254 700 678901',
    managerId: '3',
    avatarUrl: 'https://picsum.photos/seed/joses/200/200',
    status: EmployeeStatus.ACTIVE,
    hireDate: '2016-05-20',
    performanceRating: 4.0,
  },
];

export const MOCK_GOALS: Goal[] = [
  {
    id: 'g1',
    employeeId: '1',
    title: 'Expand M-Pesa Integration',
    description: 'Integrate advanced M-Pesa B2C and C2B functionalities for seamless payroll and vendor payments.',
    progress: 65,
    dueDate: '2026-12-31',
    status: 'In Progress',
  },
  {
    id: 'g2',
    employeeId: '1',
    title: 'EAC Market Expansion',
    description: 'Lead the HR strategy for opening new regional offices in Uganda and Tanzania.',
    progress: 80,
    dueDate: '2026-06-30',
    status: 'In Progress',
  },
  {
    id: 'g3',
    employeeId: '1',
    title: 'NITA Compliance Audit',
    description: 'Ensure all training records are up to date for the annual NITA reimbursement claim.',
    progress: 100,
    dueDate: '2026-03-15',
    status: 'Completed',
  },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Kenya Labor Laws 2026',
    provider: 'Federation of Kenya Employers',
    duration: '12h 30m',
    progress: 45,
    thumbnail: 'https://picsum.photos/seed/nairobi/400/225',
  },
  {
    id: 'c2',
    title: 'Digital Banking in East Africa',
    provider: 'Strathmore Business School',
    duration: '8h 15m',
    progress: 10,
    thumbnail: 'https://picsum.photos/seed/savannah/400/225',
  },
  {
    id: 'c3',
    title: 'Data Privacy Act Compliance',
    provider: 'Office of the Data Protection Commissioner',
    duration: '2h 00m',
    progress: 100,
    thumbnail: 'https://picsum.photos/seed/tech/400/225',
  },
];
